### ISSUE TITLE
Standardize `unicode_fingerprinting::FingerprintScanModule`

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/ArmorLib#13]
**Expected behavior:** **FingerprintScanModule is added to the default scan modules so that it is run on binary execution**; the scan module name matches the file name.

(To be used, scan modules must also be added on the line below.)
https://github.com/milesmcc/ArmorLib/blob/7cef7bdd316c6438f573ec83902206455e6abd6f/src/scan_modules/mod.rs#L13

**Observed behavior:** FingerprintScanModule is not added to the default scan modules so that it is run on binary execution; the scan module name (`FingerprintScanModule`) does not match the file name (`unicode_fingerprinting.rs`, should be either `fingerprint.rs` or the scan module name (and unit struct) should be changed to `UnicodeFingerprintScanModule`, the latter is prefered).

**Other notes:** the module is great nonetheless.

@nicholas-miklaucic

**Comment by nicholas-miklaucic** [comment]
This feels like code duplication: why is it necessary to both include a module and include the preprocessor? I'm not sure what better way there is to do this, but it seems like there should be some more idiomatic and concise method of doing this.
