### ISSUE TITLE
RfC: Memory v. Disk

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/ArmorLib#2]
# Request for Comment: Memory Vs Disk
There are two options for handling files. The first is to keep them stored on the disk and not load them into memory. The second is to load all files into memory. *This RfC is archived on its [RfC page](rfc/MEMORY_VS_DISK.md).*

### Advantages
* Files of any size can be safely scanned without worrying about hogging memory.
* Potentially more secure—loading files into RAM makes them possibly accessible to other programs or the CPU for potential execution.

### Disadvantages
* Redundant file IO, as each scan module would have to reload the file from the disk.
* Slow.

### Advantages
* Fast and not redundant.
* Orthodox.
* Does not assume that files will necessarily be stored on the disk.

### Disadvantages
* Could prevent large files from being processed.
* Poses a potential security risk.

---

Any and all commentary on the issue is welcome.

**Comment by darcymeyer** [comment]
Two more things to consider:

*Are you defending against an intelligent adversary?*
There is no limit to code obfuscation. If you are defending primarily against basic attacks accessible to a wide range of people, those attacks may be obvious from reading the binary. If you are dealing with an intelligent adversary, attacks may only become visible once the code is run in a virtual environment.

*What types of scans are you going to implement?*
Certain types of scans may necessitate loading the file into memory. For example, if a file is suspected of contacting a c&c server, the process of the exchange/nature of c&c server would only be observed once the malware is executed. If one scan requires loading a file into memory, you may as well load files into memory for all scan modules.

**Comment by milesmcc** [comment]
DECIDED: everything will be loaded into memory.
